// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1S8imzW0xakWbwrstzSR4ndwaGjDXRk',
    appId: '1:992946774772:web:d1769b6aa48f618359f4a1',
    messagingSenderId: '992946774772',
    projectId: 'noteappusingcode',
    authDomain: 'noteappusingcode.firebaseapp.com',
    storageBucket: 'noteappusingcode.firebasestorage.app',
    measurementId: 'G-PNHXGVC6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PzCb7FbW-YRUbULAkRrkX252SPFYBv8',
    appId: '1:992946774772:android:442bb97f561a74b359f4a1',
    messagingSenderId: '992946774772',
    projectId: 'noteappusingcode',
    storageBucket: 'noteappusingcode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPKrBWf9sWBSZNXzrE0JYGHvFdGqtdww',
    appId: '1:992946774772:ios:e4c0c263e970001059f4a1',
    messagingSenderId: '992946774772',
    projectId: 'noteappusingcode',
    storageBucket: 'noteappusingcode.firebasestorage.app',
    iosBundleId: 'com.example.noteAppUsingPara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkPKrBWf9sWBSZNXzrE0JYGHvFdGqtdww',
    appId: '1:992946774772:ios:e4c0c263e970001059f4a1',
    messagingSenderId: '992946774772',
    projectId: 'noteappusingcode',
    storageBucket: 'noteappusingcode.firebasestorage.app',
    iosBundleId: 'com.example.noteAppUsingPara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ1S8imzW0xakWbwrstzSR4ndwaGjDXRk',
    appId: '1:992946774772:web:9590fa5ee3dc316d59f4a1',
    messagingSenderId: '992946774772',
    projectId: 'noteappusingcode',
    authDomain: 'noteappusingcode.firebaseapp.com',
    storageBucket: 'noteappusingcode.firebasestorage.app',
    measurementId: 'G-LHG9DEWMNQ',
  );
}
